### ISSUE TITLE
Checklist until v0.0.1

### ISSUE THREAD

**Issue by dxu** [apophanystudios/pew#8]
- [ ] Basic Physics - gravity, acceleration, force, friction
- [ ] Camera - render view, 
- [ ] Stages - switching between game states
- [ ] Intermediate loading states
- [ ] Data store? 
- [ ] DOM integration/communication
